#!/bin/sh
#
# this is a basic script to run mythtv recordings through dvdrip.  it should be
# added as a user job to mythtv to make it nice and easy to run.  try something
# like this:
#
# mysql> select * from settings where value rlike 'userjob.*1';
# +------------------+------------------------------------------------------------------------------------------------------+----------+
# | value            | data                                                                                                 | hostname |
# +------------------+------------------------------------------------------------------------------------------------------+----------+
# | UserJobDesc1     | Archiving Video                                                                                      | NULL     |
# | UserJob1         | /bin/nice -n 10 /home/enyalios/bin/archive-recording "%TITLE%" "%SUBTITLE%" "%CHANID%" "%STARTTIME%" | NULL     |
# | JobAllowUserJob1 | 1                                                                                                    | alpha    |
# +------------------+------------------------------------------------------------------------------------------------------+----------+
# 3 rows in set (0.00 sec)

# tweak these paths as appropriate (the first 2 can also be found on my svn
# server http://svn.enyalios.net/svn/scripts/)
EPISODES="/home/enyalios/bin/episodes"
DVDRIP="/home/enyalios/bin/dvdrip"
MYTHTRANSCODE="/usr/bin/mythtranscode"

logger -t archive-recording "\"$1\" \"$2\" \"$3\" \"$4\""

# rename our arguments
title=$1
subtitle=$2
chanid=$3
starttime=$(echo $4 | perl -pe 's/^(....)(..)(..)(..)(..)..$/$1-$2-$3-$4-$5/')

# this is in case mythtv is missing subtitle data
[[ "$subtitle" == "" ]] && subtitle="unknown_episode"

cd /mnt/media/archive

# find a good filename
outfile="$($EPISODES -lu "$title" "$subtitle")"

#if it is a movie episodes will not work
[[ "$outfile" == "" ]] && outfile=$( echo $title | tr ' ' '_' )

# cut out the commercials and make a nice mpeg2 for passing to dvdrip
$MYTHTRANSCODE --chanid $chanid --starttime $starttime --outfile \
    "${outfile}.mpg" --mpeg2 --honorcutlist

# run dvdrip and strip out lots of stuff for the log files
$DVDRIP --bitrate 600 --crop --deinterlace --denoise --outfile \
    "${outfile}.mkv" --width 480 "${outfile}.mpg" 2>&1 | perl -pe 's/^.*\r(?!$)//'

rm "${outfile}.mpg" "${outfile}.mpg.map"
