#!/usr/bin/perl

use strict;
use warnings;
use LWP::UserAgent;
use MIME::Base64;
use JSON;
use POSIX qw(strftime);
use Date::Parse;

my $user = "guder\@illinois.edu";
my $pass = get_password();

sub get_password {
    my $pw = `gpg -qd ~/.password-store/password.gpg`;
    chomp $pw;
    return $pw;
}

my $start = strftime("%FT00:00:01%z", localtime(time));
my $end = strftime("%FT00:00:00%z", localtime(time + 7*24*60*60));
my $ua = LWP::UserAgent->new;
my $r = HTTP::Request->new(GET => "https://outlook.office365.com/api/v1.0/me/calendarview?\$select=Subject,Start,End,Location&StartDateTime=$start&EndDateTime=$end&orderby=Start");
my $auth = MIME::Base64::encode("$user:$pass");
$r->header(Authorization => "Basic $auth");
my $content = $ua->request($r)->{_content};

my $tree = decode_json $content;
#use Data::Dumper; print Dumper $tree;
for(@{$tree->{value}}) {
    printf "%s - %s %-28s %s\n",
    strftime("%a %b %d %R", localtime str2time $_->{Start}),
    strftime("%R", localtime str2time $_->{End}),
    $_->{Location}->{DisplayName},
    $_->{Subject};
}
