#!/bin/zsh

ZIPCODE=61820     # sets your zipcode for sun rise/set times

TRUE_STRING='user_pref("browser.display.use_document_colors", true);'
FALSE_STRING='user_pref("browser.display.use_document_colors", false);'
PREF_FILE=$(ls /home/enyalios/.mozilla/firefox/*.default/user.js)
WEATHER_URL="http://www.wunderground.com/cgi-bin/findweather/getForecast?query=$ZIPCODE"
CACHE_FILE="$HOME/.firefox-colors"
LOG_FILE="$HOME/.firefox-colors.log"
LOCK_FILE="$HOME/.firefox-colors.lock"

if [[ "$1" = "-cron" ]]; then
    shift
    if [[ -e $LOCK_FILE ]]; then
        exit 1
    fi
fi

if [[ "$1" = "default" || "$1" = "custom" ]]; then
    touch $LOCK_FILE
fi

# make a cache file if it doesnt exist with default times of 6am and 6pm
if [[ ! -e $CACHE_FILE ]]; then
    echo -e '0\n360\n1080' > $CACHE_FILE
fi

if [[ "$1" = "" ]]; then
    [[ -e $LOCK_FILE ]] && rm $LOCK_FILE
    EPOCH=$(date +%s)
    LAST_UPDATE=$(sed -ne 1p $CACHE_FILE)
    CUR_TIME=$(echo "$(date +%H)*60 + $(date +%M)" | bc)
    if [[ "`echo ${EPOCH}-${LAST_UPDATE} | bc`" -ge 86400 ]]; then # more than 24 hours old
        TIMES=$(wget -qO - $WEATHER_URL | sed -ne '/<td>Actual Time<\/td>/,+2p')
        RISE_TIME=$(echo $TIMES | sed -ne 2p | perl -pe 's/.*?>(\d+):(\d+) AM.*/$1*60 + $2/e')
        SET_TIME=$(echo $TIMES | sed -ne 3p | perl -pe 's/.*?>(\d+):(\d+) PM.*/($1 + 12)*60 + $2/e')
        if [[ ( -n $RISE_TIME && -n $SET_TIME ) ]]; then
            echo -e "$EPOCH\n$RISE_TIME\n$SET_TIME" > $CACHE_FILE
        fi
        [[ "$RISE_TIME" = "" ]] && RISE_TIME=$(sed -ne 2p $CACHE_FILE)
        [[ "$SET_TIME" = "" ]] && SET_TIME=$(sed -ne 3p $CACHE_FILE)
    else
        RISE_TIME=$(sed -ne 2p $CACHE_FILE)
        SET_TIME=$(sed -ne 3p $CACHE_FILE)
    fi
    [[ "$CUR_TIME" -ge "$SET_TIME" || "$CUR_TIME" -lt "$RISE_TIME" ]] \
        && SCHEME=custom || SCHEME=default
    #echo -e "$TIMES\nrise: $RISE_TIME\nset:  $SET_TIME\ncur:  $CUR_TIME\nscheme: $SCHEME" >> $LOG_FILE
else 
    SCHEME=$1
fi

if [ "$SCHEME" = "custom" ]; then
    if grep "$FALSE_STRING" $PREF_FILE > /dev/null ; then
        exit 0;
    fi
    sed -i "s/$TRUE_STRING/$FALSE_STRING/" $PREF_FILE
elif [ "$SCHEME" = "default" ]; then
    if grep "$TRUE_STRING" $PREF_FILE > /dev/null ; then
        exit 0;
    fi
    sed -i "s/$FALSE_STRING/$TRUE_STRING/" $PREF_FILE
else
    echo "Invalid scheme: $SCHEME"
    echo "Usage:  `basename $0` [custom|default]"
    exit 1
fi

if ps -e | grep "firefox-bin" > /dev/null; then
    [[ -x $HOME/bin/pages ]] && $HOME/bin/pages > $HOME/.pages
    export DISPLAY=:0
    # close mult windows with killall so they close at the same time.  if only 1
    # window, then use wmctrl as it closes it more cleanly
    if [[ "$(wmctrl -l | grep -c 'Mozilla Firefox')" -gt "1" ]]; then
        killall firefox-bin
    else
        wmctrl -c 'Mozilla Firefox'
    fi
    # wait up to 5 seconds for firefox to shutdown before restarting it
    for i in {1..10}; do
        if ps -e | grep -qi firefox; then
            sleep .5
        else
            firefox > /dev/null &
            exit
        fi
    done
    # if it doesnt finish in time, just kill it hard and restart it
    killall -9 firefox-bin
    firefox > /dev/null &
fi
