#!/usr/bin/perl

use strict;
use warnings;
use LWP::Simple;
use POSIX qw(strftime);

sub read_file {
    open FILE, "<", $_[0];
    my $retval = <FILE>;
    close FILE;
    chomp $retval;
    return $retval;
}

sub write_file {
    open FILE, ">", $_[0];
    print FILE $_[1];
    close FILE;
}

sub json {
    my $string = "{";
    $string .= '"name": "' . $_[0] . '",';
    $string .= '"full_text": "' . $_[1] . '",';
    if(defined $_[2] && $_[2] ne "") {
        $string .= '"color": "#' . $_[2] . '",'
    }
    $string .= '"separator_block_width": 21';
    $string .= '}';
    return $string;
}

sub weather {
    my (@stat) = stat "$ENV{HOME}/.weather";
    # file is more than 50 bytes or more than 15 minutes old
    if($stat[7] > 50 || $stat[7] < 6 || time - $stat[9] > 15*60) {
        $_ = get "http://m.wund.com/cgi-bin/findweather/getForecast?&query=" . &read_file("$ENV{HOME}/.zipcode");
        my ($temp) = /<td>Temperature.*?<b>(.*?)<\/b>/s;
        my ($cond) = /<td>Conditions.*?<b>(.*?)<\/b>/s;
        &write_file("$ENV{HOME}/.weather", "$cond $temp");
    }
    my $string = read_file("$ENV{HOME}/.weather");
    $string = "" if length $string > 50;
    my $color = "";
    $color = "8888ff" if $string =~ /snow/i;
    return &json("weather", $string, $color);
}

sub load {
    my $string = read_file("/proc/loadavg");
    $string =~ s/ .*$//;
    my $color = "";
    if($string >= 1)      { $color = "ff0000"; }
    elsif($string >= .87) { $color = "ff2a2a"; }
    elsif($string >= .75) { $color = "ff5555"; }
    elsif($string >= .62) { $color = "ff552a"; }
    elsif($string >= .50) { $color = "ff8800"; }
    elsif($string >= .37) { $color = "ffc322"; }
    elsif($string >= .25) { $color = "ffff44"; }
    elsif($string >= .12) { $color = "ffffa1"; }
    return &json("load", $string, $color);
}

sub date {
    return &json("date", strftime("%-m/%-d %T", localtime()));
}

sub battery {
    return unless -x "/usr/bin/acpi";
    my $_ = `acpi`;
    chomp;
    s/^.*?: //;
    s/^(Charg.*?%).*$/$1/;
    s/Unknown/Full/;
    y/,//d;
    my $color = "";
    if(/^Discharging /) {
        $color = "";
        (my $percent) = / (\d+)%/;
        if($percent <= 5 && time%2) { $color = "000000"; }
        elsif($percent <= 5)  { $color = "ff0000"; }
        elsif($percent <= 10) { $color = "ff0000"; }
        elsif($percent <= 15) { $color = "ff2200"; }
        elsif($percent <= 20) { $color = "ff4400"; }
        elsif($percent <= 25) { $color = "ff6600"; }
        elsif($percent <= 30) { $color = "ff8800"; }
        elsif($percent <= 35) { $color = "ffc322"; }
        elsif($percent <= 40) { $color = "ffff44"; }
        elsif($percent <= 50) { $color = "ddff7f"; }
        elsif($percent <= 60) { $color = "bbffbb"; }
        elsif($percent <= 80) { $color = "ddffdd"; }
    }
    return &json("battery", $_, $color);
}

sub watts {
    my $batt_dir = "/sys/class/power_supply/BAT0";
    return unless &read_file("$batt_dir/status") eq "Discharging";
    my $watts;
    if(-e "$batt_dir/power_now") {
        $watts = &read_file("$batt_dir/power_now");
        $watts = sprintf "%.2f", $watts/1000000;
    } elsif(-e "$batt_dir/current_now") {
        $watts = &read_file("$batt_dir/current_now");
        $watts = sprintf "%.2f", $watts/100000;
    }
    return &json("watts", "$watts W");
}

sub network {
    my $network = `network-status`;
    chomp $network;
    my $color = "";
    $color = "ff8000" if $network =~ /^Connecting to /;
    $color = "ff2a2a" if $network eq "No wireless networks found";
    return &json("network", $network, $color);
}

$| = 1;
print "{\"version\":1}\n[\n";
while(1) {
    print "[", join(",", &network(), &weather(), &battery(), &watts(), &load(), &date()), "],\n";
#    print join(" | ", &weather, &load, &date), "\n";
    sleep 1;
}
