#!/bin/sh

CAIRO_OSD="/home/enyalios/osd/cairo-osd"
#IMAGE_DIR="/home/enyalios/osd/themes/MacOSX"
IMAGE_DIR="/home/enyalios/osd/themes/Crystal"
SOUND_CHANGE="/home/enyalios/osd/sounds/audio-volume-change.oga"
export DISPLAY=:0

case $1 in
    (brightness)
        $CAIRO_OSD -t Brightness -i $IMAGE_DIR/brightness.png -p `cat /sys/class/backlight/acpi_video0/brightness`/`cat /sys/class/backlight/acpi_video0/max_brightness` &
        ;;
    (battery)
        $CAIRO_OSD -t `cat /sys/class/power_supply/BAT0/status` -i $IMAGE_DIR/battery.png -p `acpi | awk '{print $4/100}'` &
        ;;
    (volume)
        $CAIRO_OSD -t Volume -i $IMAGE_DIR/volume.png -p `amixer get PCM | perl -ne 'print "$1/100\n" if /Front Left: Playback.*\[(\d+)%\]/'` &
        mplayer $SOUND_CHANGE &
        ;;
    (mute)
        if amixer -c 29 | grep -q 'Playback \[on\]'; then
            $CAIRO_OSD -t Unmute -i $IMAGE_DIR/volume.png -p `amixer get PCM | perl -ne 'print "$1/100\n" if /Front Left: Playback.*\[(\d+)%\]/'` &
        else 
            $CAIRO_OSD -t Mute -i $IMAGE_DIR/mute.png -p 0 &
        fi
        ;;
    (suspend)
        $CAIRO_OSD -t Suspending -i $IMAGE_DIR/sleep.png
        ;;
    (hibernate)
        $CAIRO_OSD -t Hibernating -i $IMAGE_DIR/sleep.png
        ;;
    (screensaver)
        $CAIRO_OSD -t Sleeping -i $IMAGE_DIR/sleep.png
        ;;
    (touchpad)
        sleep .1
        if synclient | grep -q 'TouchpadOff.*= 1'; then
            $CAIRO_OSD -t 'Touchpad Off' -i $IMAGE_DIR/touchpad.png
        else
            $CAIRO_OSD -t 'Touchpad On' -i $IMAGE_DIR/touchpad.png
        fi
        ;;
    (charging)
        $CAIRO_OSD -t Charging -i $IMAGE_DIR/battery.png -p `acpi | awk '{print $4/100}'` &
        ;;
    (discharging)
        $CAIRO_OSD -t Battery -i $IMAGE_DIR/battery.png -p `acpi | awk '{print $4/100}'` &
        ;;
    (*)
        echo "invalid command $1"
        ;;
esac
