#!/usr/bin/perl

use warnings;
use strict;
use Sys::Syslog;

sub write_text {
    my $file = shift;
    my $string = shift;
    open(my $fh, ">", $file) or die "Couldn't open '$file': $!";
    print $fh $string;
    close $fh or die "Couldn't close '$file': $!";
}

my $VERBOSE = (defined $ARGV[0] && $ARGV[0] eq "-v")?1:0;

undef $/;

while(1) {
    open(BATTERY, "</sys/class/power_supply/BAT0/uevent") or die "couldnt find battery\n";
    my $data = <BATTERY>;
    my $discharging = ($data =~ /^POWER_SUPPLY_STATUS=Discharging/m)?1:0;
    my $remaining = ($data =~ /^POWER_SUPPLY_(?:ENERGY|CHARGE)_NOW=(\d+)$/m)[0];
    my $rate = ($data =~ /^POWER_SUPPLY_(?:POWER|CURRENT)_NOW=(\d+)$/m)[0];
    if($remaining && $rate) {
        my $time = $remaining/$rate*60;
        if($time < 3 && $discharging) { 
            openlog("acpi", "pid", "user");
            syslog("info", "battery running low, hibernating");
            closelog();
            #system("/usr/sbin/pm-hibernate");
            write_text "/sys/power/state", "disk\n";
        }
        print "discharging = $discharging\nremaining: $remaining\nrate: $rate\ntime: $time\n\n" if $VERBOSE;
    }
    sleep 60
}
