#!/usr/bin/perl

use warnings;

open LOG, "<$ENV{HOME}/minecraft/server.log" or die;
while(<LOG>) {
    $crashed = 1
    if(/^.*?\[SEVERE\] Unexpected exception$/);
    $crashed = 0
    if(/^.*?\[INFO\] Starting Minecraft server/);
    $active{$1} = 1 
    if(/^.*?\[INFO\] (.*?) \[.*?\] logged in.*$/);
    delete $active{$1} 
    if(/^.*?\[INFO\] (.*?) lost connection:.*$/);
}

if($crashed) {
    print "the minecraft server seems broken\n\n";
    exit;
}
if(%active) { 
    print "minecraft players:\n";
    print "  $_\n" for sort keys %active;
    print "\n"; 
} 
