#!/usr/bin/perl

use strict;
use warnings;
use LWP::UserAgent;
use JSON;
use File::Slurper 'read_text';
use Text::Diff;

sub sort_lines {
    my $content = $_[0];
    $content = join "\n",
    map { $_->[1]}
    sort { $a->[0] cmp $b->[0] }
    map { /^(\d+ )?(.*)$/; [ $2, $_ ]  }
    split /\n/, $content;
    return "$content\n";
}

sub get {
    my $ua = LWP::UserAgent->new();
    $ua->agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36");
    my $response = $ua->get($_[0]);
    die $response->status_line unless $response->is_success;
    return $response->decoded_content;
}


my $filename = $ARGV[0];
die "Please specify a file to read.\n" unless defined $filename;
my $file_content = read_text($filename);
my $deckid = $1 if $file_content =~ /https:\/\/moxfield.com\/decks\/(\w+)/;
die "Couldn't find a moxfield url in the file '$filename'.\n" unless defined $deckid;
my $tree = decode_json (get "https://api.moxfield.com/v2/decks/all/$deckid");
die "Couldn't find an export id for the deck.\n" unless defined $tree->{exportId};
my $moxfield_content = get "https://api.moxfield.com/v2/decks/all/$deckid/download?exportId=" . $tree->{exportId};
$moxfield_content = lc $moxfield_content;
$moxfield_content =~ s/^\s*\n//mg; # remove blank lines
$moxfield_content = sort_lines $moxfield_content;

$file_content =~ s/^[-o\/?] .*\n//mg;
$file_content =~ s/^[xp] //mg;
$file_content =~ s/ ?#.*//mg; # remove comments
$file_content =~ s/^\s*\n//mg; # remove blank lines
$file_content =~ s/ \*cmdr\*\s*$//mig;
$file_content =~ s/^(\D)/1 $1/mg; # prepend a 1 if a line doesnt have a card quantity
$file_content = lc $file_content;
$file_content = sort_lines $file_content;

print diff \$moxfield_content, \$file_content;
