#!/usr/bin/perl
#
# this script prints out which pages are currently open in firefox or mozilla.
# by default it lists firefox pages unless you pass the '-m' option for
# mozilla.  firefox 2.0 stores this information automatically, but for this
# script to work with firefox 1.x or mozilla you'll need the sessionsaver
# extension installed.  try the '-v' switch for more verbose information.

use Getopt::Std;

getopts('mv');

$dir = $opt_m?
    glob "$ENV{HOME}/.mozilla/default/*":
    glob "$ENV{HOME}/.mozilla/firefox/*.default";

$file = (-e "$dir/sessionstore.js")?
    "$dir/sessionstore.js":
    "$dir/prefs.js";

die unless open(INPUT, "<$file");

if($file eq "$dir/sessionstore.js") { 
    @tabs = split /index:(\d+)/, <INPUT>; 
    close INPUT;
    while($tabs[$i]) { 
        ($_, $index) = @tabs[$i, $i+1]; 
        last if /_closedTabs:/; 
        @urls = /url:"(.*?)"/g; 
        print $urls[$index - 1], "\n"; $i += 2; 
    }
} else {
    @lines = <INPUT>;
    $num_sessions = grep { /sessionsaver\.windows\.session/ } @lines;
    for(@lines) {
        next unless /sessionsaver\.windows\.session/;
        ($session_num, $string) = /^.*?".*?(\d+)".*?(z1[ |].+)  ?\d+"\);$/; 
        next unless $string;
        @tabs = split /[ |]\|\|/, $string;
        print "Session $session_num:\n" if $num_sessions > 1;
        for(@tabs) {
            ($hist_num, $string) = /z1[ |]\|(\d+)[ |]\|-?\d+,-?\d+\| ?(.*)/;
            @urls = split /[ |]\|-?\d+,-?\d+\| ?/, $string;
            if($opt_v) { print "hist_num: $hist_num\n"; print "  $_\n" for @urls };
            print "$urls[$hist_num]\n";
        }
    }
}

close INPUT;
