#!/bin/bash

# re-exec ourselves with sudo if not root
[[ "$UID" -ne "0" ]] && exec sudo $0 $@

JOBS=$(($(cat /proc/cpuinfo | grep MHz | wc -l) + 1))
RED=$(echo -ne "\e[1;31m")
BLUE=$(echo -ne "\e[1;34m")
CYAN=$(echo -ne "\e[1;36m")
DEFAULT=$(echo -ne "\e[0m")
MOUNTED_BOOT="0"

check_exit_code() {
    CODE=$1
    MSG=$2
    if [[ "$CODE" -ne "0" ]]; then
        echo "${RED}${MSG}${DEFAULT}"
        exit $CODE
    fi
}

check_for_new_kernel() {
    # skip kernel stuff if we arent using the gentoo-kernel package
    if ! grep -q '^sys-kernel/gentoo-kernel' /var/lib/portage/world; then
        return
    fi

    # we do the grep so messages about eselect news dont throw off the count
    if [[ "$(emerge --quiet --pretend --update gentoo-kernel | grep gentoo-kernel | wc -l)" -gt "0" ]]; then
        mount /boot 2>/dev/null
        [[ "$?" -eq  "0" ]] && MOUNTED_BOOT=1
        echo "${CYAN}A new kernel will be installed."
        echo "  Please remove the oldest one to make space"
        echo "  in /boot, and then press enter to continue.${DEFAULT}"
        read
    fi
}

header() {
    echo "${BLUE}### $1 ${DEFAULT}"
}

check_for_new_kernel

header "emerge @world"
emerge --quiet-build --update --deep --ask --verbose --newuse --jobs $JOBS @world
check_exit_code "$?" "Died emerging world."

find '/etc' -name '._cfg????_*' | grep -q . && header "dispatch-conf"
dispatch-conf

header "emerge @preserved-rebuild"
emerge --quiet-build --ask --verbose --jobs $JOBS @preserved-rebuild
check_exit_code "$?" "Died during rebuild."

find '/etc' -name '._cfg????_*' | grep -q . && header "dispatch-conf"
dispatch-conf

header "emerge depclean"
emerge --ask --depclean
check_exit_code "$?" "Died during depclean."

NEWS=$(eselect news list | awk '{if($2=="N")print}')
echo "$NEWS" | grep -q . && header "eselect news"
echo "$NEWS"

if [[ "$(uname -r)" != "$(eselect kernel list | sed -ne 's/.*linux-\([.0-9]*\) \*/\1/p')" ]]; then
    if [[ -e "/usr/sbin/grub-mkconfig" ]]; then
        header "reconfiguring grub"
        grub-mkconfig -o /boot/grub/grub.cfg
        check_exit_code "$?" "Died during grub reconfiguration."
        echo "${CYAN}New kernel installed, please reboot!${DEFAULT}"
    else
        echo "${CYAN}New kernel installed, please edit grub config and reboot!${DEFAULT}"
    fi
fi

[[ "$MOUNTED_BOOT" -eq "1" ]] && umount /boot

# TODO
# update perl modules in ~/perl5
# remove old kernels
# keep n old kernels

# kernel removal steps
# edit grub config
# emerge -Ca gentoo-kernel-5.4.40
# rm /boot/System.map-5.4.40  /boot/config-5.4.40  /boot/initramfs-5.4.40.img  /boot/vmlinuz-5.4.40
# rm -rf /lib/modules/5.4.40
# rm -rf /usr/src/linux-5.4.40
