#!/usr/bin/perl
#
# update your card database with this command:
# wget -O - 'http://ww2.wizards.com/gatherer/Index.aspx?output=Text+Spoiler' | perl -pe 'BEGIN { undef $/ } s/^.*?\n<table class="TextResultsTable" border="0">\n//s; s/\n<\/table>.*?$//s; s/\r//g;' | perl -pe 's/<.*?>//g; s/^((?:CardName|Cost|Type|Pow\/Tgh|Rules Text|Set\/Rarity):)?/sprintf "%-13.13s", $1/e; s/^ *&nbsp;&nbsp;//; s/\xC3\x86/AE/g; s/oSi/S/g;' > ~/magic/oracle

use strict;
use warnings;

$/ = "\n\n";
my $count = 0;
my $names = 1, shift if $ARGV[0] eq "-n";
my %cards;

open INPUT, "<$ENV{HOME}/magic/oracle" or die "cant find input file\n";

CARD: while(<INPUT>) {
    for my $regex (@ARGV) {
        next CARD unless /$regex/im;
    }
    my ($card_name) = /^CardName: +(.*)$/m;
    next CARD if $cards{$card_name}++;
    if($names) { 
        print "$card_name\n" and next CARD;
    } else {
        1 while s/^(?=.{81})(.{0,80})( +.*)/$1\n              $2/m;
        print;
        $count++;
    }
}

close INPUT;

print "$count card(s) returned\n\n" unless $names;
